package com.betx.domain.order;

import com.betx.domain.signal.BetSide;
import java.math.BigDecimal;
import java.time.Instant;

/** Persisted live bet execution intent, regardless of the trigger channel. */
public record BetIntent(
    String id,
    BetIntentSource source,
    String exchange,
    String marketId,
    long selectionId,
    String eventName,
    String marketName,
    String runnerName,
    String competitionName,
    SelectionSide selectionSide,
    String strategyName,
    BetSide side,
    String reason,
    BigDecimal odds,
    BigDecimal maxStake,
    BigDecimal availableBalance,
    BigDecimal effectiveAvailableBalance,
    BigDecimal reservedBalance,
    Instant balanceSnapshotAt,
    BigDecimal selectedStake,
    String resultMessage,
    String externalOrderId,
    Instant settledAt,
    BetSettlementResult settlementResult,
    BigDecimal realizedProfitLoss,
    BetIntentStage stage,
    Instant createdAt,
    Instant updatedAt,
    String evaluationId,
    String recommendationId,
    Instant recommendedAt,
    BigDecimal recommendedOdds,
    Instant orderSubmittedAt,
    Instant orderResponseAt,
    Instant orderAcceptedAt,
    Instant executedAt,
    BigDecimal requestedOdds,
    BigDecimal averageExecutedOdds,
    BigDecimal requestedStake,
    BigDecimal matchedStake,
    BigDecimal remainingStake,
    BetExecutionStatus executionStatus
) {
    public BetIntent {
        id = id == null ? null : id.strip();
        if (source == null) {
            source = BetIntentSource.TELEGRAM_CONFIRMATION;
        }
        exchange = exchange == null ? null : exchange.strip();
        marketId = marketId == null ? null : marketId.strip();
        eventName = eventName == null ? null : eventName.strip();
        marketName = marketName == null ? null : marketName.strip();
        runnerName = runnerName == null ? null : runnerName.strip();
        competitionName = competitionName == null ? null : competitionName.strip();
        selectionSide = selectionSide == null ? SelectionSide.UNKNOWN : selectionSide;
        strategyName = strategyName == null ? null : strategyName.strip();
        if (side == null) {
            side = BetSide.BACK;
        }
        reason = reason == null ? null : reason.strip();
        resultMessage = resultMessage == null ? null : resultMessage.strip();
        externalOrderId = externalOrderId == null ? null : externalOrderId.strip();
        evaluationId = evaluationId == null || evaluationId.isBlank() ? null : evaluationId.strip();
        recommendationId = recommendationId == null || recommendationId.isBlank() ? null : recommendationId.strip();
        if (stage == null) {
            stage = BetIntentStage.AWAITING_CONFIRMATION;
        }
        if (createdAt == null) {
            createdAt = Instant.now();
        }
        if (updatedAt == null) {
            updatedAt = createdAt;
        }
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal selectedStake,
        String resultMessage,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            null,
            SelectionSide.UNKNOWN,
            null,
            BetSide.BACK,
            reason,
            odds,
            maxStake,
            availableBalance,
            null,
            null,
            null,
            selectedStake,
            resultMessage,
            null,
            null,
            null,
            null,
            stage,
            createdAt,
            updatedAt,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    public BetIntent(
        String id,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal selectedStake,
        String resultMessage,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            BetIntentSource.TELEGRAM_CONFIRMATION,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            reason,
            odds,
            maxStake,
            availableBalance,
            selectedStake,
            resultMessage,
            stage,
            createdAt,
            updatedAt
        );
    }

    public BetIntent(
        String id,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            BetIntentSource.TELEGRAM_CONFIRMATION,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            reason,
            odds,
            maxStake,
            availableBalance,
            selectedStake,
            resultMessage,
            externalOrderId,
            stage,
            createdAt,
            updatedAt
        );
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            null,
            SelectionSide.UNKNOWN,
            null,
            reason,
            odds,
            maxStake,
            availableBalance,
            selectedStake,
            resultMessage,
            externalOrderId,
            stage,
            createdAt,
            updatedAt
        );
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String competitionName,
        SelectionSide selectionSide,
        String strategyName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            BetSide.BACK,
            reason,
            odds,
            maxStake,
            availableBalance,
            null,
            null,
            null,
            selectedStake,
            resultMessage,
            externalOrderId,
            null,
            null,
            null,
            stage,
            createdAt,
            updatedAt,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal effectiveAvailableBalance,
        BigDecimal reservedBalance,
        Instant balanceSnapshotAt,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            null,
            SelectionSide.UNKNOWN,
            null,
            reason,
            odds,
            maxStake,
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            stage,
            createdAt,
            updatedAt
        );
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String competitionName,
        SelectionSide selectionSide,
        String strategyName,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal effectiveAvailableBalance,
        BigDecimal reservedBalance,
        Instant balanceSnapshotAt,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            BetSide.BACK,
            reason,
            odds,
            maxStake,
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            null,
            null,
            null,
            stage,
            createdAt,
            updatedAt
        );
    }

    public BetIntent(
        String id,
        BetIntentSource source,
        String exchange,
        String marketId,
        long selectionId,
        String eventName,
        String marketName,
        String runnerName,
        String competitionName,
        SelectionSide selectionSide,
        String strategyName,
        BetSide side,
        String reason,
        BigDecimal odds,
        BigDecimal maxStake,
        BigDecimal availableBalance,
        BigDecimal effectiveAvailableBalance,
        BigDecimal reservedBalance,
        Instant balanceSnapshotAt,
        BigDecimal selectedStake,
        String resultMessage,
        String externalOrderId,
        Instant settledAt,
        BetSettlementResult settlementResult,
        BigDecimal realizedProfitLoss,
        BetIntentStage stage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            side,
            reason,
            odds,
            maxStake,
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            createdAt,
            updatedAt,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    public String displayRunner() {
        return runnerName == null || runnerName.isBlank() ? String.valueOf(selectionId) : runnerName;
    }

    public BetIntent withId(String newId) {
        return new BetIntent(
            newId,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            side,
            reason,
            odds,
            maxStake,
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            createdAt,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    public BetIntent withEvaluationId(String newEvaluationId) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            newEvaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    public BetIntent withRecommendation(String newRecommendationId, Instant newRecommendedAt, BigDecimal newRecommendedOdds) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            evaluationId,
            newRecommendationId,
            newRecommendedAt,
            newRecommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    public BetIntent withOrderSubmitted(Instant submittedAt, BigDecimal newRequestedOdds, BigDecimal newRequestedStake) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            submittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            newRequestedOdds,
            averageExecutedOdds,
            newRequestedStake,
            matchedStake,
            remainingStake,
            BetExecutionStatus.SUBMITTED
        );
    }

    public BetIntent withOrderResponse(Instant responseAt, BetExecutionStatus newExecutionStatus) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            responseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            newExecutionStatus
        );
    }

    public BetIntent withExchangeExecutionSnapshot(
        Instant newExecutedAt,
        BigDecimal newAverageExecutedOdds,
        BigDecimal newMatchedStake,
        BigDecimal newRemainingStake,
        BetExecutionStatus newExecutionStatus
    ) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            newMatchedStake == null || newMatchedStake.compareTo(BigDecimal.ZERO) <= 0 ? null : newExecutedAt,
            requestedOdds,
            newAverageExecutedOdds,
            requestedStake,
            newMatchedStake,
            newRemainingStake,
            newExecutionStatus
        );
    }

    public BetIntent withStage(BetIntentStage newStage, BigDecimal balance, BigDecimal stake) {
        return withStage(newStage, balance, stake, resultMessage);
    }

    public BetIntent withStage(BetIntentStage newStage, BigDecimal balance, BigDecimal stake, String message) {
        return withStageAt(newStage, balance, stake, message, Instant.now());
    }

    public BetIntent withStageAt(
        BetIntentStage newStage,
        BigDecimal balance,
        BigDecimal stake,
        String message,
        Instant updatedAt
    ) {
        return copy(
            balance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            stake,
            message,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            newStage,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    public BetIntent withExternalOrderId(String newExternalOrderId) {
        return copy(
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            resultMessage,
            newExternalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    public BetIntent withSettlement(
        BetIntentStage newStage,
        BetSettlementResult newSettlementResult,
        BigDecimal newRealizedProfitLoss,
        Instant newSettledAt,
        String message
    ) {
        return new BetIntent(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            side,
            reason,
            odds,
            maxStake,
            availableBalance,
            effectiveAvailableBalance,
            reservedBalance,
            balanceSnapshotAt,
            selectedStake,
            message,
            externalOrderId,
            newSettledAt,
            newSettlementResult,
            newRealizedProfitLoss,
            newStage,
            createdAt,
            newSettledAt == null ? Instant.now() : newSettledAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            BetExecutionStatus.SETTLED
        );
    }

    public BetIntent withExecutionBalanceAudit(
        BigDecimal newEffectiveAvailableBalance,
        BigDecimal newReservedBalance,
        Instant newBalanceSnapshotAt
    ) {
        return new BetIntent(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            side,
            reason,
            odds,
            maxStake,
            availableBalance,
            newEffectiveAvailableBalance,
            newReservedBalance,
            newBalanceSnapshotAt,
            selectedStake,
            resultMessage,
            externalOrderId,
            settledAt,
            settlementResult,
            realizedProfitLoss,
            stage,
            createdAt,
            updatedAt,
            evaluationId,
            recommendationId,
            recommendedAt,
            recommendedOdds,
            orderSubmittedAt,
            orderResponseAt,
            orderAcceptedAt,
            executedAt,
            requestedOdds,
            averageExecutedOdds,
            requestedStake,
            matchedStake,
            remainingStake,
            executionStatus
        );
    }

    private BetIntent copy(
        BigDecimal newAvailableBalance,
        BigDecimal newEffectiveAvailableBalance,
        BigDecimal newReservedBalance,
        Instant newBalanceSnapshotAt,
        BigDecimal newSelectedStake,
        String newResultMessage,
        String newExternalOrderId,
        Instant newSettledAt,
        BetSettlementResult newSettlementResult,
        BigDecimal newRealizedProfitLoss,
        BetIntentStage newStage,
        Instant newUpdatedAt,
        String newEvaluationId,
        String newRecommendationId,
        Instant newRecommendedAt,
        BigDecimal newRecommendedOdds,
        Instant newOrderSubmittedAt,
        Instant newOrderResponseAt,
        Instant newOrderAcceptedAt,
        Instant newExecutedAt,
        BigDecimal newRequestedOdds,
        BigDecimal newAverageExecutedOdds,
        BigDecimal newRequestedStake,
        BigDecimal newMatchedStake,
        BigDecimal newRemainingStake,
        BetExecutionStatus newExecutionStatus
    ) {
        return new BetIntent(
            id,
            source,
            exchange,
            marketId,
            selectionId,
            eventName,
            marketName,
            runnerName,
            competitionName,
            selectionSide,
            strategyName,
            side,
            reason,
            odds,
            maxStake,
            newAvailableBalance,
            newEffectiveAvailableBalance,
            newReservedBalance,
            newBalanceSnapshotAt,
            newSelectedStake,
            newResultMessage,
            newExternalOrderId,
            newSettledAt,
            newSettlementResult,
            newRealizedProfitLoss,
            newStage,
            createdAt,
            newUpdatedAt,
            newEvaluationId,
            newRecommendationId,
            newRecommendedAt,
            newRecommendedOdds,
            newOrderSubmittedAt,
            newOrderResponseAt,
            newOrderAcceptedAt,
            newExecutedAt,
            newRequestedOdds,
            newAverageExecutedOdds,
            newRequestedStake,
            newMatchedStake,
            newRemainingStake,
            newExecutionStatus
        );
    }
}
