package com.betx.application;

/** Conservative diagnostics-only reason for recommendation_id paper/real divergence. */
public enum DiagnosticsRecommendationDivergenceReason {
    REAL_BLOCKED_BY_RISK_MAX_OPEN_POSITIONS,
    REAL_BLOCKED_BY_RISK_DAILY_LOSS,
    REAL_BLOCKED_BY_ACTIVE_MARKET_INTENT_EXISTS,
    REAL_BLOCKED_BY_DUPLICATE_GUARD,
    REAL_REJECTED_BY_CONFIRMATION,
    REAL_SKIPPED_BY_CONFIG,
    REAL_NOT_ATTEMPTED,
    REAL_DEPENDENCY_ERROR,
    REAL_ORDER_FAILED,
    MARKET_CLOSED_BEFORE_REAL,
    TIMING_WINDOW_MISMATCH,
    MISSING_REAL_LOG_CONTEXT,
    PAPER_NOT_CREATED,
    PAPER_DISABLED,
    PAPER_SKIPPED_BY_DEDUP,
    PAPER_EXECUTION_FAILED,
    PAPER_MARKET_SCAN_FAILED,
    PAPER_SETTLEMENT_OR_MARKET_DATA_ERROR,
    PAPER_DEPENDENCY_ERROR,
    MARKET_CLOSED_BEFORE_PAPER,
    MISSING_PAPER_LOG_CONTEXT,
    UNKNOWN
}
